import { readFileSync, writeFileSync, readdirSync } from "fs";
import { join, basename } from "path";
import { optimize } from "svgo";

const ICONS_DIR = join(import.meta.dirname, "icons");
const OUT_FILE = join(import.meta.dirname, "generated.ts");

function toPascalCase(name: string): string {
  return name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");
}

function optimizeSvg(source: string): string {
  const result = optimize(source, {
    plugins: [
      {
        name: "preset-default",
        params: {
          overrides: {
            removeViewBox: false,
            inlineStyles: { onlyMatchedOnce: false },
          },
        },
      },
      "removeDimensions",
    ],
  });
  return result.data;
}

function extractInner(svg: string): string {
  return svg.replace(/<svg[^>]*>/, "").replace(/<\/svg>/, "").trim();
}

function buildIconFunction(name: string, inner: string): string {
  const pascal = toPascalCase(name);
  return `
export function ${pascal}(props: IconProps = {}): string {
  const {
    size = 24,
    color = "currentColor",
    strokeWidth = 2,
    class: className,
  } = props;
  const cls = className ? \` class="\${className}"\` : "";
  return \`<svg viewBox="0 0 24 24" fill="none" stroke="\${color}" stroke-width="\${strokeWidth}" stroke-linecap="square" stroke-linejoin="miter" width="\${size}" height="\${size}"\${cls} xmlns="http://www.w3.org/2000/svg">${inner}</svg>\`;
}`;
}

const svgFiles = readdirSync(ICONS_DIR)
  .filter((f) => f.endsWith(".svg"))
  .sort();

const names: string[] = [];
const functions: string[] = [];

for (const file of svgFiles) {
  const name = basename(file, ".svg");
  const source = readFileSync(join(ICONS_DIR, file), "utf-8");
  const optimized = optimizeSvg(source);
  const inner = extractInner(optimized);
  names.push(name);
  functions.push(buildIconFunction(name, inner));
}

const iconMap = names
  .map((n) => `  "${n}": ${toPascalCase(n)}`)
  .join(",\n");

const output = `// SPDX-FileCopyrightText: AnmiTaliDev <anmitalidev@nuros.org>
// SPDX-License-Identifier: AGPL-3.0-only
// This file is auto-generated by src/build.ts — do not edit manually.

import type { IconProps, SwissIconName } from "./types";
${functions.join("\n")}

const iconMap: Record<SwissIconName, (props?: IconProps) => string> = {
${iconMap},
};

export function getIcon(name: SwissIconName, props?: IconProps): string {
  const fn = iconMap[name];
  if (!fn) throw new Error(\`@swiss-ui/icons: unknown icon "\${name}"\`);
  return fn(props);
}

export type { SwissIconName, IconProps };
`;

writeFileSync(OUT_FILE, output, "utf-8");
console.log(`Generated ${names.length} icons → src/generated.ts`);
